[tool.black]
line-length = 99
target-version = ["py310"]
include = '\.pyi?$'

[tool.ruff]
line-length = 99
target-version = "py310"
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "D",   # pydocstyle
    "B",   # flake8-bugbear
]
ignore = [
    "D100",  # Missing docstring in public module
    "D104",  # Missing docstring in public package
]

[tool.ruff.per-file-ignores]
"tests/**/*" = ["D103"]  # Missing docstring in public function

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true

[[tool.mypy.overrides]]
module = ["tests.*"]
disallow_untyped_defs = false

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
addopts = "-v -s --durations=0"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning",
]
